#!/bin/sh
#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2026 Johannes Brügmann
#
# elvbootd -- the runtime watch of the platform-trust chain: NOT a process
# but a family of hook scripts plugged into FreeBSD's own mechanisms, one
# per bound phase, generated by `elebake stage elvbootd mk <stage>` from
# this catalog (same contract as earlboot/policy.sh; the generated hooks
# share earlboot's prologue, constants and word check). Every hook leaves
# a heartbeat under $ELV_STATE that the next earlboot run claims -- the
# watchdog is itself watched.
#
# Phases of this container (elebake reads this line):
PHASES="STARTUP PERIODIC RESUME MEDIA"
#   STARTUP   one-shot rc.d late in the boot (network is up): beacon, attest
#   PERIODIC  periodic/security, daily: the media, the loader, the book
#   RESUME    rc.resume, after every wake: the clock gap, the medium
#   MEDIA     devd, when a removable medium appears ($1 = the cdev)

# --- firing predicates (identical to earlboot's; the runtime flags come
# from the persisted appraisal of the last boot, read in the prologue) ---

when_always() { return 0; }
when_fail()   { [ "$GATE_VERDICT" = fail ]; }
when_pass()   { [ "$GATE_VERDICT" = pass ]; }
when_skipped() { [ -n "$SKIPPED" ]; }

when_maybe() {
	local s
	s=$(/usr/bin/od -An -tu4 -N4 /dev/urandom | /usr/bin/tr -d ' ')
	[ -n "$s" ] || s=2463534242
	s=$(( (s ^ (s << 13)) & 0xffffffff )); s=$(( (s ^ (s >> 17)) & 0xffffffff )); s=$(( (s ^ (s << 5)) & 0xffffffff ))
	[ $((s & 3)) -eq 0 ]
}

when_tainted()  { [ "$ELV_TAINT" = 1 ] || [ "$GATE_VERDICT" = fail ]; }
when_duress()   { [ "$ELV_DURESS" = 1 ]; }
when_prompted() { [ "$ELV_PROMPTED" = 1 ]; }

# elv_prologue -- what the generated hook runs after the functions and
# before its phase (every container defines one; the emitter calls it)
elv_prologue() {
	elv_flags_load
}

# elv_flags_load -- the flags of this boot as earlboot persisted them
# (persist_act); absent appraisal = flags unknown = 0
elv_flags_load() {
	local f
	ELV_WORD_OK=0; ELV_TAINT=0; ELV_DURESS=0; ELV_PROMPTED=0
	f="$ELV_STATE/appraisal-$ELV_GATE_LOADER"
	[ -f "$f" ] || return 0
	ELV_WORD_OK=$(/usr/bin/sed -n 's/^word=\([01]\) .*/\1/p' "$f")
	ELV_TAINT=$(/usr/bin/sed -n 's/.* taint=\([01]\) .*/\1/p' "$f")
	ELV_DURESS=$(/usr/bin/sed -n 's/.* duress=\([01]\) .*/\1/p' "$f")
	ELV_PROMPTED=$(/usr/bin/sed -n 's/.* prompted=\([01]\)$/\1/p' "$f")
	return 0
}
