#!/bin/sh
#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2026 Johannes Brügmann
#
# elvbootd -- the runtime watch of the platform-trust chain: NOT a process
# but a family of hook scripts plugged into FreeBSD's own mechanisms, one
# per bound phase, generated by `elebake stage elvbootd mk <stage>` from
# this catalog (same contract as earlboot/policy.sh; the generated hooks
# share earlboot's prologue, constants and word check). Every hook leaves
# a heartbeat under $ELV_STATE that the next earlboot run claims -- the
# watchdog is itself watched.
#
# Phases of this container (elebake reads this line):
PHASES="STARTUP PERIODIC RESUME MEDIA"
#   STARTUP   one-shot rc.d late in the boot (network is up): beacon, attest
#   PERIODIC  periodic/security, daily: the media, the loader, the book
#   RESUME    rc.resume, after every wake: the clock gap, the medium
#   MEDIA     devd, when a removable medium appears ($1 = the cdev)

# --- firing predicates (identical to earlboot's; the runtime flags come
# from the persisted appraisal of the last boot, read in the prologue) ---

# Composition: a trigger record may combine these -- and(a,b), or(a,b),
# not(a) -- and name several actions, compose(a,b). The emitter renders the
# combination as { a && b; }, { a || b; }, ! a, and the actions in order;
# nothing here needs to know.
# when_always -- every time
when_always() { return 0; }
# when_fail -- the gate's overall verdict is fail
when_fail()   { [ "$GATE_VERDICT" = fail ]; }
# when_pass -- the gate's overall verdict is pass
when_pass()   { [ "$GATE_VERDICT" = pass ]; }
# when_skipped -- at least one claim of the gate was skipped: its measurement
# returned nothing, so no verdict was possible
when_skipped() { [ -n "$SKIPPED" ]; }

# when_maybe -- about one run in four, a spot check an observer cannot time.
# xorshift32 seeded from the entropy device: noise, not cryptography; only
# ever ADDS a spot check.
when_maybe() {
	local s
	s=$($OD -An -tu4 -N4 /dev/urandom | $TR -d ' ')
	[ -n "$s" ] || s=2463534242
	s=$(( (s ^ (s << 13)) & 0xffffffff )); s=$(( (s ^ (s >> 17)) & 0xffffffff )); s=$(( (s ^ (s << 5)) & 0xffffffff ))
	[ $((s & 3)) -eq 0 ]
}

# when_tainted -- the handover word carried taint, or this gate failed
when_tainted()  { [ "$ELV_TAINT" = 1 ] || [ "$GATE_VERDICT" = fail ]; }
# when_duress -- the handover word carried the duress bit; bind only SILENT
# actions here, the coercer must see nothing
when_duress()   { [ "$ELV_DURESS" = 1 ]; }
# when_prompted -- an interactive action ran in the loader
when_prompted() { [ "$ELV_PROMPTED" = 1 ]; }

# elv_prologue -- what the generated hook runs after the functions and
# before its phase (every container defines one; the emitter calls it)
elv_prologue() {
	elv_flags_load
}

# elv_flags_load -- the flags of this boot as earlboot persisted them
# (persist_act); absent appraisal = flags unknown = 0
elv_flags_load() {
	local f
	ELV_WORD_OK=0; ELV_TAINT=0; ELV_DURESS=0; ELV_PROMPTED=0
	f="$ELV_STATE/appraisal-$ELV_GATE_LOADER"
	[ -f "$f" ] || return 0
	ELV_WORD_OK=$($SED -n 's/^word=\([01]\) .*/\1/p' "$f")
	ELV_TAINT=$($SED -n 's/.* taint=\([01]\) .*/\1/p' "$f")
	ELV_DURESS=$($SED -n 's/.* duress=\([01]\) .*/\1/p' "$f")
	ELV_PROMPTED=$($SED -n 's/.* prompted=\([01]\)$/\1/p' "$f")
	return 0
}
