/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2026 Johannes Brügmann
 */

/*
 * foundation.c -- GENERATED BY ELEBAKE. This file is the empty shell.
 *
 * The real foundation.c is compiled from the stage's decisions by
 *
 *     elebake stage foundation make <stage>
 *
 * (project elvboot, https://github.com/enk-ode/elvboot): the baseline macro
 * blocks from site.mk, the prerequisites lists, the GATE_DEFINEs with their
 * claims and secret slots, the per-phase policy tables and phase_policies().
 * elebake writes it into the stage's worktree right before the build; the
 * shell here only keeps an unprovisioned tree linking: no prerequisites, no
 * gates, no policies -- every phase runs nothing, the loader behaves like
 * stock. Do not edit; do not add gates here.
 */

#include "measurement.h"
#include "claim.h"
#include "policy.h"			/* pulls gate.h (gates) + action.h (actions) */

const char *const prerequisites_exist[] = { NULL };
const char *const prerequisites_verify[] = { NULL };
const unsigned int prerequisites_exist_n = 0;
const unsigned int prerequisites_verify_n = 0;

static const struct policy no_policies[] = {
	POLICY_END,
};

const struct policy *
phase_policies(enum phase ph __unused)
{
	return (no_policies);
}
